2021-07-18 20:42:33.005 | INFO     | __main__:serve:63 - 启动服务：127.0.0.1:8091
2021-07-18 20:43:13.041 | ERROR    | grpc._server:_call_behavior:444 - An error has been caught in function '_call_behavior', process 'MainProcess' (95470), thread 'ThreadPoolExecutor-0_0' (123145344442368):
Traceback (most recent call last):

  File "/Users/jianxiyan/anaconda3/envs/mxshop_srvs/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x10f4e50d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145344442368)>
  File "/Users/jianxiyan/anaconda3/envs/mxshop_srvs/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x10f4e2dc0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145344442368)>
  File "/Users/jianxiyan/anaconda3/envs/mxshop_srvs/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145344442368)>
    │    │        │    └ (<weakref at 0x111406f40; to 'ThreadPoolExecutor' at 0x1113851f0>, <_queue.SimpleQueue object at 0x111377a90>, None, ())
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145344442368)>
    │    └ <function _worker at 0x111393f70>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145344442368)>
  File "/Users/jianxiyan/anaconda3/envs/mxshop_srvs/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x11138f0d0>
    └ <concurrent.futures.thread._WorkItem object at 0x111404f40>
  File "/Users/jianxiyan/anaconda3/envs/mxshop_srvs/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x111404f40>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x111406a90>, <grpc._server._RPCState object at 0x111404d90>, <bound method ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x111404f40>
             │    └ <function _unary_response_in_pool at 0x111402700>
             └ <concurrent.futures.thread._WorkItem object at 0x111404f40>
  File "/Users/jianxiyan/anaconda3/envs/mxshop_srvs/lib/python3.8/site-packages/grpc/_server.py", line 561, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method UserServicer.GetUserList of <user_srv.handler.user.UserServicer object at 0x1113e4100>>
                        │              │          └ <grpc._server._RPCState object at 0x111404d90>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x111406a90>
                        └ <function _call_behavior at 0x111402310>
> File "/Users/jianxiyan/anaconda3/envs/mxshop_srvs/lib/python3.8/site-packages/grpc/_server.py", line 444, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x11140e340>
                           │        └ pn: 1
                           │          pSize: 10
                           │          
                           └ <bound method UserServicer.GetUserList of <user_srv.handler.user.UserServicer object at 0x1113e4100>>

  File "/Users/jianxiyan/home/练习/go_python/mxshop/mxshop_srvs/user_srv/handler/user.py", line 52, in GetUserList
    rsp.data.append(self.convert_user_to_rsp(user))
    │   │           │    │                   └ <User: 1>
    │   │           │    └ <function UserServicer.convert_user_to_rsp at 0x110f9b1f0>
    │   │           └ <user_srv.handler.user.UserServicer object at 0x1113e4100>
    │   └ <field property 'UserListResponse.data'>
    └ total: 11

  File "/Users/jianxiyan/home/练习/go_python/mxshop/mxshop_srvs/user_srv/handler/user.py", line 30, in convert_user_to_rsp
    user_info_rsp.birthDay = int(time.mktime(user.birthday.timetuple()))
    │                            │    │      │    └ <peewee.FieldAccessor object at 0x111375f70>
    │                            │    │      └ <User: 1>
    │                            │    └ <built-in function mktime>
    │                            └ <module 'time' (built-in)>
    └ id: 1
      password: "$pbkdf2-sha256$29000$d45RqlXq3dv7PweAsNY6xw$vxT290H3kIK/ELtrz01nhrFkmATvbnKHcdLOLLjOGhk"
      mobile: "1878222222...

AttributeError: 'UserInfoResponse' object has no attribute 'birthDay'
2021-07-18 20:44:36.090 | ERROR    | grpc._server:_call_behavior:444 - An error has been caught in function '_call_behavior', process 'MainProcess' (95470), thread 'ThreadPoolExecutor-0_0' (123145344442368):
Traceback (most recent call last):

  File "/Users/jianxiyan/anaconda3/envs/mxshop_srvs/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x10f4e50d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145344442368)>
  File "/Users/jianxiyan/anaconda3/envs/mxshop_srvs/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x10f4e2dc0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145344442368)>
  File "/Users/jianxiyan/anaconda3/envs/mxshop_srvs/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145344442368)>
    │    │        │    └ (<weakref at 0x111406f40; to 'ThreadPoolExecutor' at 0x1113851f0>, <_queue.SimpleQueue object at 0x111377a90>, None, ())
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145344442368)>
    │    └ <function _worker at 0x111393f70>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145344442368)>
  File "/Users/jianxiyan/anaconda3/envs/mxshop_srvs/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x11138f0d0>
    └ <concurrent.futures.thread._WorkItem object at 0x11140e580>
  File "/Users/jianxiyan/anaconda3/envs/mxshop_srvs/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x11140e580>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x11085d950>, <grpc._server._RPCState object at 0x11140e340>, <bound method ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x11140e580>
             │    └ <function _unary_response_in_pool at 0x111402700>
             └ <concurrent.futures.thread._WorkItem object at 0x11140e580>
  File "/Users/jianxiyan/anaconda3/envs/mxshop_srvs/lib/python3.8/site-packages/grpc/_server.py", line 561, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method UserServicer.GetUserList of <user_srv.handler.user.UserServicer object at 0x1113e4100>>
                        │              │          └ <grpc._server._RPCState object at 0x11140e340>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x11085d950>
                        └ <function _call_behavior at 0x111402310>
> File "/Users/jianxiyan/anaconda3/envs/mxshop_srvs/lib/python3.8/site-packages/grpc/_server.py", line 444, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x11140ef70>
                           │        └ pSize: 2
                           │          
                           └ <bound method UserServicer.GetUserList of <user_srv.handler.user.UserServicer object at 0x1113e4100>>

  File "/Users/jianxiyan/home/练习/go_python/mxshop/mxshop_srvs/user_srv/handler/user.py", line 52, in GetUserList
    rsp.data.append(self.convert_user_to_rsp(user))
    │   │           │    │                   └ <User: 1>
    │   │           │    └ <function UserServicer.convert_user_to_rsp at 0x110f9b1f0>
    │   │           └ <user_srv.handler.user.UserServicer object at 0x1113e4100>
    │   └ <field property 'UserListResponse.data'>
    └ total: 11

  File "/Users/jianxiyan/home/练习/go_python/mxshop/mxshop_srvs/user_srv/handler/user.py", line 30, in convert_user_to_rsp
    user_info_rsp.birthDay = int(time.mktime(user.birthday.timetuple()))
    │                            │    │      │    └ <peewee.FieldAccessor object at 0x111375f70>
    │                            │    │      └ <User: 1>
    │                            │    └ <built-in function mktime>
    │                            └ <module 'time' (built-in)>
    └ id: 1
      password: "$pbkdf2-sha256$29000$d45RqlXq3dv7PweAsNY6xw$vxT290H3kIK/ELtrz01nhrFkmATvbnKHcdLOLLjOGhk"
      mobile: "1878222222...

AttributeError: 'UserInfoResponse' object has no attribute 'birthDay'
2021-07-18 20:46:47.634 | INFO     | __main__:on_exit:20 - 注销成功9f2d53a4-e7c5-11eb-8f5f-acde48001122
